export const GAME_SPEED = 1
export const BOT_RADIUS = 8
export const BOT_COUNT = 100
export const EMTY_SPACE_DECREASE = 0.18
export const GRAVITY = -1
export const MAX_GREEN_ENERGY = 2.5
export const CORE_ANTIGRAVITY = 5
export const MAX_GRAVITY_DISTANCE = BOT_RADIUS * 30
export const CORE_DISTANCE_MULTIPLE = 1.5
export const MIN_GRAVITY_DISTANCE = 1
export const MAX_ENERGY = 200
